CREATE DATABASE INTERVIEW;
USE INTERVIEW;
CREATE TABLE CUSTOMER
(
CUSTOMER_ID INT PRIMARY KEY,
CUSTOMER_NAME VARCHAR(30),
CUSTOMER_PHONE VARCHAR(12),
CUSTOMER_ADD VARCHAR(40),
CUST_MAIL VARCHAR(36)

);

DROP TABLE CUSTOMER;

INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_PHONE,CUSTOMER_ADD) VALUES (100,'Hennath','8976543290',' CHENNAI'),
(200,'John','7654321235','MADHYA PRADESH'),(300,'vinay','6543218908','MUMBAI'),(400,'KAVIYA','7877666660','GUINDY');


CREATE TABLE PRODUCT(
PRODUCT_ID INT PRIMARY KEY,
PRODUCT_NAME VARCHAR(20),
PRODUCT_STATUS VARCHAR(30),
CUSTOMER_ID INT,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

DROP TABLE PRODUCT;

INSERT INTO PRODUCT(PRODUCT_ID,PRODUCT_NAME,PRODUCT_STATUS,CUSTOMER_ID) VALUES(99,'Laptop','Delivered Monday',100);


SELECT * FROM CUSTOMER;

SELECT * FROM PRODUCT;

DESC product;

SHOW COLUMNS FROM CUSTOMER;

ALTER TABLE CUSTOMER
ADD COLUMN CUST_EMAIL VARCHAR(10);


SELECT * FROM CUSTOMER;

ALTER TABLE CUSTOMER
DROP COLUMN CUSTOMER_ADDRESS;


ALTER TABLE CUSTOMER
ADD COLUMN CUSTOMER_ADD VARCHAR(15);

INSERT INTO CUSTOMER(CUSTOMER_ID,CUSTOMER_ADD) VALUES (100,'MUMBAI'),(200,'CHENNAI'),(300,'LONDON'),(400,'PARIS');

UPDATE CUSTOMER
SET CUST_MAIL = CUSTOMER_ADD;

SELECT * FROM CUSTOMER;

SELECT * FROM CUST;


ALTER TABLE CUSTOMER
MODIFY COLUMN CUST_MAIL VARCHAR(60);


SHOW COLUMNS FROM CUSTOMER;

RENAME TABLE CUSTOMER TO CUST;


ALTER TABLE CUST
RENAME COLUMN CUST_MAIL TO MAIL;


RENAME TABLE CUST TO CUSTOMER;

SELECT * FROM CUSTOMER;

ALTER TABLE CUSTOMER
MODIFY COLUMN CUSTOMER_PHONE CHAR(200);

SHOW COLUMNS FROM CUSTOMER;

ALTER TABLE CUSTOMER
ADD COLUMN CUST_STATUS VARCHAR(20);

SELECT * FROM CUSTOMER;


ALTER TABLE CUSTOMER
RENAME COLUMN  CUSTOMER_ADD TO ADDRESS;



SELECT * FROM CUST;
RENAME TABLE CUSTOMER TO CUST;


ALTER TABLE  CUST  RENAME COLUMN CUST_STATUS TO C_STATUS;

RENAME TABLE CUST TO CUSTOMER;

SELECT * FROM CUSTOMER;

ALTER TABLE CUSTOMER
DROP COLUMN C_STATUS;

SELECT * FROM CUSTOMER;

TRUNCATE TABLE CUSTOMER;
DROP TABLE EMPLOYEE;
USE INTERVIEW;
CREATE TABLE EMPLOYEE
(
EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
EMP_NAME VARCHAR(20) DEFAULT 'NAME IS NOT ASSIGNED',
EMP_AGE INT NOT NULL, 
EMP_SALARY INT ,
CHECK (EMP_SALARY >50000)
);

INSERT INTO EMPLOYEE(EMP_AGE,EMP_SALARY) VALUES (22,40000);

SELECT * FROM EMPLOYEE; 


CREATE TABLE STUDENT
(
STUD_ID INT PRIMARY KEY,
STUD_NAME VARCHAR(20),
STUD_AGE INT,
STUD_MAIL VARCHAR(20),
STUD_INTEREST VARCHAR(30)
);


-- ADDING NOT NULL USING MODIFY 
ALTER TABLE STUDENT
MODIFY COLUMN STUD_INTEREST VARCHAR(20) NOT NULL;
-- DROP NOT NULL 
ALTER TABLE STUDENT
MODIFY COLUMN STUD_INTEREST VARCHAR(27);
 -- ADD DEFAULT CONSTRAINT
 ALTER TABLE STUDENT
 ALTER COLUMN STUD_MAIL SET DEFAULT 'MAIL NOT NEED';

-- DROP DEFAULT CONSTRAINT
ALTER TABLE STUDENT
ALTER STUD_MAIL DROP DEFAULT;


-- ADD CHECK 
-- DROP CHECK
-- ALTER

ALTER TABLE STUDENT
MODIFY COLUMN STUD_NAME CHAR(30);


ALTER TABLE STUDENT
ALTER column STUD_MAIL set DEFAULT 'mail@gmail.com';


ALTER TABLE STUDENT
ADD CHECK(STUD_AGE>20);


INSERT INTO STUDENT(STUD_ID,STUD_NAME,STUD_AGE,STUD_MAIL) VALUES(2,'KAVIYA',22,'kavi@gmail,com');

SELECT * FROM STUDENT;

INSERT INTO STUDENT(STUD_ID,STUD_NAME,STUD_AGE) VALUES (4,'GEETHA',24);

INSERT INTO STUDENT(STUD_ID,STUD_NAME,STUD_AGE,STUD_MAIL)VALUES (6,'SEETHA',8,'seetha@gmail.com');

SELECT * FROM STUDENT;


ALTER TABLE STUDENT
ADD CONSTRAINT check_age CHECK(STUD_AGE>1);

ALTER TABLE STUDENT
DROP CHECK check_age;

ALTER TABLE STUDENT
DROP CHECK CHECK_SAL;


ALTER TABLE STUDENT
ADD CONSTRAINT check_interest CHECK(STUD_MAIL='KAVI');

DROP TABLE DEMO;
SELECT * FROM DEMO;
CREATE TABLE DEMO
(
ID INT PRIMARY KEY NOT NULL,
DEMO_NAME VARCHAR(20),
MARKS INT
);


ALTER TABLE DEMO
ALTER DEMO_NAME SET DEFAULT 'HAI';


INSERT INTO DEMO (ID,MARKS) VALUES (20,90);

SELECT * FROM DEMO;

ALTER TABLE DEMO
ALTER DEMO_NAME SET DEFAULT 'HAI';

