USE DEMO;
-- ---------------------------------------------------------------
-- IN MYSQL       --- THERE IS NO IDENTITY FUNCTION
-- AUTO_INCREMENT IS THERE IN MYSQL AND COMPULSORY ONE AUTO INCREMENT COLUMN ALLOWED
-- THAT ALSO ALLOWED ALONG WITH KEYS LIKE PRIMARY KEY OR UNIQUE KEY ETC.,
-- ----------------------------------------------------------------

SHOW TABLES;
CREATE TABLE EMP
(
ID INT AUTO_INCREMENT PRIMARY KEY,
FULL_NAME VARCHAR(40)
);

INSERT INTO EMP (FULL_NAME) VALUES ('Kaviya');
INSERT INTO EMP (FULL_NAME)VALUES('Seetha');

SELECT * FROM EMP;

-- IF WE GIVE THE SEED VALUE MEAN
-- AUTO_INCREMENT = 100
-- NOW THE STARTING VALUE IS 100 
-- FOR EACH ROW THIS WILL BE INCREMENTED BY 1
-- WE CAN ALSO USE TRIGGERS TO FORCEFULLY MAKE HOW MUCH IT SHOULD INCREMENTED
-- I WILL DO THIS TRIGGERS IN UPCOMING TOPICS


CREATE TABLE EMPLOYEE
(
ID INT AUTO_INCREMENT UNIQUE,
FULL_NAME VARCHAR(40)
)
AUTO_INCREMENT=100;

INSERT INTO EMPLOYEE (FULL_NAME)VALUES ('KAVIYA'),('SEETHA'),('RAM'),('VINAY');

SELECT * FROM EMPLOYEE;





