-- DDL commands
-- create alter drop rename truncate

USE SQL_FULL;

ALTER TABLE STAFF DROP COLUMN JOIN_DATE;
SELECT * FROM STAFF;

DESC STAFF;

ALTER TABLE STAFF 
MODIFY COLUMN AGE VARCHAR(20);

ALTER TABLE STAFF
MODIFY COLUMN AGE INT;

ALTER TABLE STAFF RENAME TO NEW_STAFF;
SELECT * FROM NEW_STAFF;

ALTER TABLE NEW_STAFF RENAME COLUMN DOB TO DATA_OF_BIRTH;
SELECT * FROM NEW_STAFF;

ALTER TABLE NEW_STAFF RENAME TO STAFF;
SELECT * FROM STAFF;

ALTER TABLE STAFF RENAME COLUMN FIRST_NAME  TO FULL_NAME;
SELECT * FROM STAFF;


ALTER TABLE STAFF ADD CONSTRAINT UNIQUE_STAFF UNIQUE (STAFF_TYPE);

ALTER TABLE STAFF ADD COLUMN JOIN_DATE DATE;

SELECT * FROM STAFF;