USE DEMO;

SHOW TABLES;
-- DML DATA MANIPULATION LANGUAGE 
-- MANIPULATE THE DATE IN THE TABLE
-- INSERT UPDATE DELETE

-- INSERT CAN BE DONE IN 2 WAYS
    -- ONE WILL BE -- IF THE TABLE CONTAINS 4 COLUMN THEN WE CAN GIVE 4 VALUES
    -- INSERT INTO TABLE_NAME VALUES(1,2,3,4);
    
    -- ANOTHER WILL BE -- IF THE TABLE CONTAINS 4 COLUMN BUT I WANT TO AADD ONLY 2
    -- COLUMN THEN  MENTION THE COLUMN NAME AND SEND 2 VALUES
    -- INSERT INTO TABLE_NAME (COLUMN-1,COLUMN-2) VALUES(1,2);
    
DROP TABLE STUDENT;

CREATE TABLE STUDENT
( 
STUD_ID INT ,
STUD_NAME VARCHAR(20),
AGE INT,
FEES DECIMAL(6,2)
);


-- WITHOUT INTO KEYWORD IN INSERT STATEMENT
INSERT STUDENT VALUES(200,'Kaviya',22,9000);


-- INSERT ALL THE VALUES OF ALL THE COLUMN
INSERT INTO STUDENT VALUES(100,'DHANU',25,5000);
SELECT * FROM STUDENT;

-- INSERT ONLY PARTICULAR COLUMN BY MENTIONING THE COLUMN NAME
INSERT INTO STUDENT (STUD_ID,STUD_NAME,FEES) VALUES(300,'JAI RAM',3000);

-- ------------------------------ UPDATE COMMAND -------------------------------------
-- UPDATE PARTICULAR COLUMN USING WHERE CONDITION
-- IF WE NOT MENTION THE WHERE CONDITION THEN IT UPDATE ALL THE ROWS
-- HERE WE NOT GIVE ANY WHERE CONDITION SO THIS AGE IS UPDATED IN ALL THE ROWS:

UPDATE STUDENT
SET AGE=22;

SELECT * FROM STUDENT;
-- UPDATE THE PARTICULAR COLUMN USING WHERE CLAUSE
UPDATE STUDENT
SET AGE = 23 WHERE STUD_ID=100;

-- -------------------------------------- DELETE COMMANDS ------------------------------

-- WE CAN DELETE THE PARTICULAR COLUMN IN THE TABLE
-- IF WE NOT USING WHERE CONDITION THEN ALL THE RECORDS IN THE TABLE TO BE DELETED
-- ONLY THE RECORDS ARE DELETED NOT THE STRUCTURE OF THE TABLE


-- BELOW WILL DELETE ONLY THE PARTICULAR COLUMN
DELETE FROM STUDENT
WHERE STUD_ID=300;

-- BELOW WILL DELETE ALL THE ROWS EXCEPT THE STRUCTURE OF THE TABLE
DELETE FROM STUDENT;

-- IS OPERATOR
UPDATE STUDENT SET AGE=33 WHERE AGE IS NULL;
SELECT * FROM STUDENT;


DELETE FROM STUDENT WHERE AGE IS NOT NULL;
SELECT * FROM STUDENT;









