-- DATA MANIPULATION LANGUAGE
  -- INSERT
           -- LOAD DATA INTO TABLE
           -- INSERT INTO TABLE_NAME (COLUMN_NAME) VALUES (ROW_NAME-1),(ROW_NAME-2) ...ETC
           -- WE CAN INSERT AS MANY ROWS AS WE WANT
           -- SEPERATED BY COMMAS
           -- ITS OPTIONAL TO MENTION THE COLUMN NAME
           
  -- UPDATE
		 -- MODIFY DATA IN TABLE
         -- UPDATE TABLE_NAME SET COLUMN_NAME = 'COLUMN_VALUE'
         -- WHERE  COLUMN_NAME='VALUE' 
         
  -- DELETE
          -- DELETE DATA FROM THE TABLE
          -- DELETE FROM TABLE_NAME
          -- DELETE FROM TABLE_NAME WHERE COLUMN_NAME=COLUMN_VALUE;
  -- MERGE 