-- we can use logical operators, = != <> < > <=  >=
--  LIKE ,BETWEEN , IN , NOT IN, DISTINCT ,AND , OR, LIMIT ,CASE ,OFFSET 
USE SQL_FULL;
SELECT * FROM STAFF;
USE SQL_FULL;

SELECT FULL_NAME FROM STAFF WHERE FULL_NAME LIKE '%N';
SELECT AGE FROM STAFF WHERE AGE>30;
SELECT AGE,FULL_NAME FROM STAFF WHERE AGE>30 AND GENDER='M';
SELECT FULL_NAME,STAFF_TYPE FROM STAFF WHERE STAFF_TYPE IN('NON-TEACHING');
SELECT FULL_NAME,STAFF_TYPE FROM STAFF WHERE STAFF_TYPE NOT IN('NON-TEACHING');

ALTER TABLE STAFF RENAME COLUMN DATA_OF_BIRTH TO DOB;
SELECT * FROM STAFF;

SELECT DOB FROM STAFF WHERE DOB BETWEEN '1980-02-01' AND '1994-04-01' ;

SELECT FULL_NAME FROM STAFF LIMIT 1;

SELECT DISTINCT STAFF_TYPE FROM STAFF;

SELECT  STAFF_TYPE FROM STAFF LIMIT 2 OFFSET 1;

SELECT FULL_NAME,AGE,GENDER,
CASE 
WHEN AGE=22 THEN 'PERFECT AGE TO START WORK'
WHEN AGE>=35 THEN 'SAVE MONEY'
WHEN AGE>29 THEN 'SPEND TIME'
END AS AGE_CATEGORY
FROM STAFF;













