-- RELATIONAL --- > TABLE KEY VALUES   SQL
-- NON RELATIONAL ----> JSON ,GRAPHS ,FILE,KEY VALUE PAIRS.,ETC  
             -- ------>NOSQL
-- DBMS DATABASE MANAGEMENT SYSTEM -- 
-- DBMS---> SPECIAL SOFTWARE WHERE WE CAN WRITE THE SQL STATEMENTS
-- DBMS IS A WORKSPACE
-- ORACLE
-- MYSQL 
-- MICROSOFT SQL SERVER
-- POSTGRE SQL
-- DATABASE   
                -- COLLECTION OF DATA IN CERTAIN FORMAT
                -- MYSQL IS NOT CASE SENSITITVE
                -- WE CAN USE BOTH UPPER AND LOWER CASE
                -- CREATE DATABASE DATABASENAME
                -- USE DATABASENAME
                
CREATE DATABASE SAMPLE;
USE SAMPLE;
SHOW DATABASES;
DROP DATABASE SAMPLE;
-- CREATE TABLE TABLE_NAME(COLUMN-1 DATATYPE ,COLUMN-2 DATATYPE);
-- INSERT INTO TABLE_NAME (COLUMN-NAME) VALUES(VALUE1,VALUE2,VALUE3);

-- DISPLAY ALL RECORDS
SELECT * FROM EMP;

-- SELECT PARTICULAR COLUMN 
SELECT FULL_NAME FROM EMP;

-- ADD NEW COLUMN TO THE TABLE
ALTER TABLE EMP 
ADD COLUMN EMAIL VARCHAR(20);

-- ADD VALUE TO NEWLY ADDED COLUMN OR UPDATE
UPDATE EMP SET EMAIL="kaviya@gmail.com" where id=1;
UPDATE EMP SET EMAIL="newmail22.com";

-- DELETE A COLUMN FROM THE TABLE
ALTER TABLE EMP
DROP COLUMN EMAIL;

SELECT * FROM EMP;

-- DELETE THE RECORD FROM THE TABLE
DELETE FROM EMP WHERE ID=1;


-- DELETE THE TABLE
DROP TABLE EMP;

-- CREATE TABLE
CREATE TABLE EMP (ID INT,FULLNAME VARCHAR(30));
INSERT INTO EMP VALUES(1,'Jai'),(2,'raj'),(3,'vinay'),(4,'raghu');

ALTER TABLE EMP
MODIFY COLUMN ID VARCHAR(20);

DESCRIBE EMP;

-- VIEW SPECIFIC ROW
SELECT * FROM EMP LIMIT 3;












