CREATE DATABASE SQL_FULL;

USE  SQL_FULL;


CREATE TABLE ADDRESS
(
ADDRESS_ID VARCHAR(10),
STREET VARCHAR(20),
CITY VARCHAR(15),
STATE VARCHAR(30),
COUNTRY VARCHAR(26),
CONSTRAINT PK_ADDRESS_ID PRIMARY KEY (ADDRESS_ID)
);

CREATE TABLE SCHOOL
(
SCHOOL_ID VARCHAR(20),
SCHOOL_NAME VARCHAR(30),
EDUCATION_BOARD VARCHAR(15),
ADDRESS_ID VARCHAR(10),
CONSTRAINT PK_SCHOOL_ID PRIMARY KEY(SCHOOL_ID),
CONSTRAINT FK_ADDRESS_ID FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);

INSERT INTO ADDRESS (ADDRESS_ID,STREET,CITY,STATE,COUNTRY)VALUES('ADDR001','GANDHI NAGAR','SALEM','TAMILNADU','INDIA');
INSERT INTO ADDRESS (ADDRESS_ID,STREET,CITY,STATE,COUNTRY)VALUES('ADDR002','THILLAI NAGAR','CHENNAI','TAMILNADU','INDIA');
INSERT INTO ADDRESS (ADDRESS_ID,STREET,CITY,STATE,COUNTRY)VALUES('ADDR003','RAM NAGAR','BANGALORE','KARNATAKA','IND');
INSERT INTO SCHOOL(SCHOOL_ID,SCHOOL_NAME,EDUCATION_BOARD,ADDRESS_ID) VALUES ('SCH001','GRS GROUP OF INSTITUTION','STATEBOARD','ADDR001');

SELECT * FROM ADDRESS;

SELECT * FROM SCHOOL;

DROP TABLE STAFF;

CREATE TABLE STAFF
(
STAFF_ID VARCHAR(20),
STAFF_TYPE VARCHAR(30),
SCHOOL_ID VARCHAR(20),
FIRST_NAME VARCHAR(40) NOT NULL,
LAST_NAME VARCHAR(35) NOT NULL,
AGE INT,
DOB DATE,
GENDER VARCHAR(2) CHECK (GENDER IN('M','F')),
JOIN_DATE DATE,
ADDRESS_ID VARCHAR(10),
CONSTRAINT PK_STAFF_ID PRIMARY KEY(STAFF_ID),
CONSTRAINT FK_STAFF_SCHOOL_ID FOREIGN KEY(SCHOOL_ID) REFERENCES SCHOOL(SCHOOL_ID),
CONSTRAINT FK_STAFF_ADD_ID FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);


SET SQL_MODE = 'NO_ZERO_DATE,NO_ZERO_IN_DATE';


INSERT INTO STAFF (STAFF_ID,STAFF_TYPE,SCHOOL_ID,FIRST_NAME,LAST_NAME,AGE,DOB,GENDER
,JOIN_DATE,ADDRESS_ID)VALUES
('STF001','TEACHING','SCH001','KAVIYA','CHINNAKAVAN',22, STR_TO_DATE('02/04/2001','%m/%d/%Y'),'F', STR_TO_DATE('09/23/2023','%m/%d/%Y'),'ADDR001'),
('STF002','NON-TEACHING','SCH001','SHAJAHAN','SHARUK' ,35, STR_TO_DATE('10/02/1981','%m/%d/%Y'),'M', STR_TO_DATE('05/03/2010','%m/%d/%Y'),'ADDR002'),
('STF003','NON-TEACHING','SCH001','SMRITHI','MADHAVAN',30, STR_TO_DATE('09/24/1991','%m/%d/%Y'),'F', STR_TO_DATE('01/29/2015','%m/%d/%Y'),'ADDR003');


DESCRIBE STAFF;
SELECT * FROM STAFF;

